config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/homepage", to: "homepage#index", as: :homepage
  get "/menuitems", to: "menuitems#index", as: :new_menuitems
  post "/menuitems", to: "menuitems#create"
  get "menuitems/:id", to: "menuitems#show"
  get "/orders/new" => "orders#new", as: :carts
  post "/orders/confirm" => "orders#confirm"
  post "/deliverorder/:id" => "orders#deliverOrder"
  #get "/menus", to: "menus#index", as: :menus
  get "/" => "home#new", as: :home
  get "/users/new" => "users#new", as: :new_users
  post "/users/new" => "users#create", as: :users
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  get "/orders", to: "orders#index"
  get "/reports" => "reports#index", as: :reports
  get "/reports/:id" => "reports#invoice", as: :invoice
  #get "/menuitems/cart", to: "menuitems#cart", as: :new_cartitems
  #post "/menuitems/cart", to: "menuitems#new", as: :cartitems
  delete "/exit" => "menusessions#destroy", as: :destroy_menusession
  delete "/signout" => "sessions#destroy", as: :destroy_session
  #post "/orderitems" => "orderitems#create"
  post "/cart/:id" => "order_items#cart", as: :cart
  get "/orders/:id" => "orders#show", as: :order
  delete "/order_items/:id" => "order_items#destroy"
  get "/order_items/:id" => "order_items#change"

  resources :orders
  resources :menus
  resources :menuitems
  resources :users
  resources :order_items
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in


  def new
    if current_user
      redirect_to menus_path
    else
      render "home/new"
    end
  end
end

app/views/home/new.html.erb
<div class="nline, bg">

<h1 class="Home-Title">Welcome to the cafeteria manager</h1>
<p class="Home-Text">Enjoy delicious food at our Restaurant</p>
<h3 class="Home-Authenticate">New to use Cafeteria Manager then <%= link_to "sign up here", new_users_path %> </h3>
<h3 class="Home-Authenticate">An existing user? then <%= link_to "sign in here", new_sessions_path %> </h3>
<p style="display: flex;"><br><hr>
<div style="display: flex;"><p class="Owner-Page">Owner blog then <%= link_to "sign in here", new_sessions_path %></p>
<p class="Clerk-Page">Clerk blog then <%= link_to "sign-in here", new_sessions_path %></p></div>
</p>
</div>