config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/homepage", to: "homepage#index", as: :homepage
  get "/menuitems", to: "menuitems#index", as: :new_menuitems
  post "/menuitems", to: "menuitems#create"
  get "menuitems/:id", to: "menuitems#show"
  get "/orders/new" => "orders#new", as: :carts
  post "/orders/confirm" => "orders#confirm"
  post "/deliverorder/:id" => "orders#deliverOrder"
  #get "/menus", to: "menus#index", as: :menus
  get "/" => "home#new", as: :home
  get "/users/new" => "users#new", as: :new_users
  post "/users/new" => "users#create", as: :users
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  get "/orders", to: "orders#index"
  get "/reports" => "reports#index", as: :reports
  get "/reports/:id" => "reports#invoice", as: :invoice
  #get "/menuitems/cart", to: "menuitems#cart", as: :new_cartitems
  #post "/menuitems/cart", to: "menuitems#new", as: :cartitems
  delete "/exit" => "menusessions#destroy", as: :destroy_menusession
  delete "/signout" => "sessions#destroy", as: :destroy_session
  #post "/orderitems" => "orderitems#create"
  post "/cart/:id" => "order_items#cart", as: :cart
  get "/orders/:id" => "orders#show", as: :order
  delete "/order_items/:id" => "order_items#destroy"
  get "/order_items/:id" => "order_items#change"

  resources :orders
  resources :menus
  resources :menuitems
  resources :users
  resources :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :menuitem
  def self.ordered_items(id)
    OrderItem.all.where(order_id: id)
  end
end

app/models/orderitem.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :menu_item
  def self.ordered_items(id)
    OrderItem.all.where(order_id: id)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
    render "index"
  end

  def show
    id = params[:id]
    session[:current_order_id] = id
    orderitem = OrderItem.find(id)
    render "order-content", locals: { orderitem: orderitem }
  end

  def create
  end

  def new
    render "new"
  end

  def change
    order_item = Order.find(session[:current_order_id]).order_items.find_by(menuitem_id: params[:id])
    if params[:menu_item_quantity].to_i > 0
      if order_item
        order_item.menu_item_quantity = params[:menu_item_quantity]
        order_item.save
      else
        render "cart"
      end
    else
      if order_item
        order_item.destroy
      end
    end
    redirect_to menus_path
  end

  def cart
    id = params[:id]
    menuitem = Menuitem.find(id)
    menuitem_name = menuitem.name
    menuitem_price = menuitem.price
    new_orderitem = OrderItem.create!(order_id: session[:current_order_id],
                                      menuitem_id: menuitem.id,
                                      menuitem_name: menuitem.name,
                                      menuitem_price: menuitem.price,
                                      menu_item_quantity: params[:menu_item_quantity])
    if new_orderitem.save
      flash[:success] = "#{params[:menuitem_name]} added to  cart!"
    end

    redirect_to "/order_items"
  end

  def destroy
    id = params[:id]
    orderitem = OrderItem.find(id)
    orderitem.destroy
    redirect_to "/order_items"
  end
end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  def index
  end

app/views/order_items/index.html.erb
<article>
<% if @current_user.role == "customer" || @current_user.role == "clerk" %>
    <h1 style="font-size:50px">Items in cart are:</h1>
    <% OrderItem.all.each do |orderitem| %>
      <div class="Item-Text">
       <% if session[:current_order_id] == orderitem.order_id %>
          Item name: <%= orderitem.menuitem_name %><br>
          Price: $<%= orderitem.menuitem_price %><br>
          Quantity: <%= orderitem.menu_item_quantity %>

           <%= form_with(url: "/order_items/#{orderitem.id}", method: "delete") do %>
                  <%= image_submit_tag("trash.svg", class: "cart-trash")%>
           <% end %>
        <% end %>


      </div>

      <% end %>

      <h3 class="Add-Item"><%= link_to "Add More Items", "/menus/#{session[:current_menu_id]}" %></h3>
      <h3 class="Add-Item"><%= link_to "Finalise", carts_path %></h3>

<% end %>
</article>